---
title: "4th Year Workshop"
subtitle: "Publishing"
author: Ian McCarthy, Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```

# Publishing

The publication process, particularly in economics, is crazy. We'll go over some basics in these slides.

---
# The Steps

A successful publication journey looks something like...

1. Do all the work.
2. Submit
3. Editor review
4. Referee review
5. Comments to author for revise and resubmit
6. Review again
7. Conditionally accept (minor typos etc.)
8. Accept


--
If only life were this simple!

---
# Step 2: Submit

- Formatting: Look at the journal's formatting guidelines
- Adopt where it is easy to do so
- Pay attention to page/word limits
- Don't worry about very specific formatting (save it for publication)
- Include all required elements (disclosure statements, etc.)

---
# Step 3: Editor review

- After quick review for basics, paper goes to an editor
- May sit at editor's desk for several weeks
- Be patient and vow to **not** do that once you are an editor!
- Editor can reject unilaterally without reviews (desk rejection)

---
# Step 4: Referee review

If you "made it past the desk", the it goes to peer review

- May sit at reviwers' desks for many months
- Remember this feeling and vow to **not** do that once you are a reviewer!
- **Do not** check the status of your paper constantly


--
Nothing good can come from this. It's like checking EJMR. 

