---
title: "4th Year Workshop"
subtitle: "Understanding the job market"
author: Ian McCarthy, Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```

# The Job Market

The academic job market can be intimidating and somewhat confusing. These slides are intended to provide a basic overview and timeline of what to expect as you prepare for and enter the job market next year. See this [guide](https://www.aeaweb.org/content/file?id=869) for more detail.

---
# Are you ready?

Two questions to ask before you really prepare for the job market:

1. Will you have a finished (and sufficiently strong) JMP completed by the Fall?
2. Will you be in a position to defend in the following Spring?


--
Getting an actual job requires a lot of informal networking from advisers...make sure you and your adviser are on the same page!


---
# Pre-market

- From now until August
- Prepare your materials (papers, short-videos or visual abstracts, CV, syllabus)
- Complete your website
- Prepare committee members and letter writers
- Identify job preferences


---
count: false

# Pre-market

- Submit your JMP to conferences
- Eastern and Midwest Economics Association in March
- Western Economic Association in June-July
- Southern Economic Association in November
- [Young Economists Symposium](https://wp.nyu.edu/gsas-yes/)
- Western Economics Association [Graduate Student Dissertation Workshop](https://weai.org/conferences/view/2/94th-Annual-Conference#learn-more)

---
# On the academic market

- Submit applications in Fall
- Application review in November(ish)
- Interview requests soon after
- Short interviews at AEAs or virtual
- Fly outs in early Spring


---
count: false

# On the academic market

- You are **always** interviewing
- Be careful at all conferences, not just AEAs


---
# On the non-academic market

- More fluid
- Interviews around the same time for large consulting firms
- Looking for different things (more about this in 5th year workshop)


---
# Preparing yourself

Some things to keep in mind...

- The job market is stressful, especially the academic market
- It is a **two-sided** matching problem...you need to assess fit as well
- Be kind and patient with others and with yourself
- There exists (for worse) a trickle down component of the academic market
- You **will** leave the PhD with a job (0.9% unemployment rate among doctoral programs)
- You **can** be happy in any job you choose