---
title: "4th Year Workshop"
subtitle: "Understanding the job market"
author: "Ian McCarthy, Emory University"
institute: "Economics PhD Professionalism Workshop"
---

# The Job Market

The academic job market can be intimidating and somewhat confusing. These slides are intended to provide a basic overview and timeline of what to expect as you prepare for and enter the job market next year. See this [guide](https://www.aeaweb.org/content/file?id=869) for more detail.

---

# Are you ready?

Two questions to ask before you really prepare for the job market:

1. Will you have a finished (and sufficiently strong) JMP completed by the Fall?
2. Will you be in a position to defend in the following Spring?


. . .

Getting an actual job requires a lot of informal networking from advisers...make sure you and your adviser are on the same page!


---

# Pre-market

- From now until August
- Prepare your materials (papers, short-videos or visual abstracts, CV, syllabus)
- Complete your website
- Prepare committee members and letter writers
- Identify job preferences


---

# Pre-market

- Submit your JMP to conferences
- Eastern and Midwest Economics Association in March
- Western Economic Association in June-July
- Southern Economic Association in November
- [Young Economists Symposium](https://wp.nyu.edu/gsas-yes/)
- Western Economics Association [Graduate Student Dissertation Workshop](https://weai.org/conferences/)

---

# On the academic market

- Submit applications in Fall
- Application review in November(ish)
- Interview requests soon after
- Short interviews at AEAs or virtual
- Fly outs in early Spring


---

# On the academic market

- You are **always** interviewing
- Be careful at all conferences, not just AEAs


---

# On the non-academic market

- More fluid
- Interviews around the same time for large consulting firms
- Looking for different things (more about this in 5th year workshop)


---

# Preparing yourself

Some things to keep in mind...

- The job market is stressful, especially the academic market
- It is a **two-sided** matching problem...you need to assess fit as well
- Be kind and patient with others and with yourself
- There exists (for worse) a trickle down component of the academic market
- You **will** leave the PhD with a job (0.9% unemployment rate among doctoral programs)
- You **can** be happy in any job you choose
