---
title: "Professional Etiquette"
subtitle: "Improving the Workplace Culture"
author: "Ian McCarthy, Emory University"
institute: "Economics PhD Professionalism Workshop"
---

# Culture

What can you do to help improve the culture?

- Be professional and treat others with respect (we already know this one)
- Maintain regular hours and be present
- Say hi and step out of your office every now and then

---

# Regular hours

- Typically required for non-academic jobs
- My opinion: Should be required for academic jobs too
  - Others should know who you are
  - Students should be able to stop by outside of office hours (especially close advisees and PhD students)
  - Faculty should want to help other faculty
- Try leaving your door open

. . .

It's super depressing to walk through a whole department and just see closed doors or vacant offices everywhere.

---

# Interact

This is harder to do for introverts, but...

- Ask people to go to coffee or tea
- Go for walks
- Go out to lunch

. . .

Try to be part of your workplace. It's much more rewarding.
