---
title: "Professional Etiquette"
subtitle: "i.e. Uncommon Common Sense"
author: Ian McCarthy | Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```

# Table of contents

1. [Motivation](#welcome)
2. [Email](#email)
3. [Meetings](#meetings)
4. [Golden Rule](#goldenrule)


---
# General Etiquette

- Give others the benefit of the doubt
- Always assume you made the mistake until proven otherwise
- Respect others' time

--

Others means **everyone**, not just "other professors"


<!-- New Section -->
---
class: inverse, center, middle
name: welcome

# Motivation

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Why?

Isn't this common sense? Don't we all know what it means to "be professional"?

--
Um...apparently not!

---
# Exhibit A

Student:
> This may be a stupid question, but --

Professor:
> It is.

---
# Exhibit B

Professor begins selling books on e-bay that were received (for free) from publishers. Uses department resources to package and ship books for free too.

---
# Exhibit C

Professor emails department explaining why their preferred job candidate is great and so much better than another professor in the department

---
# Exhibit D

Professor proclaims in a department meeting that a junior professor is much better than other people the department has promoted, with said promotee in meeting

---
# Exhibit E

Job candidate asked about "working papers" on their CV. Job candidate reveals them to be poorly thought-out ideas at best, with no paper to speak of.

---
# Exhibit F

Break room note...




<!-- New Section -->
---
class: inverse, center, middle
name: email

# Email

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Respond

- Use your professional email account!
  - "Oh, he doesn't check that email address. Did you send it to this other address?" 
- Respond to your emails!!
  - Equilibrium where we all need multiple reminders is bad
- Respond with complete thoughts
- Respond in a respectful way
- Be **very careful** with reply all


---
# Difficult conversions via email 

Once you hit send, the email is available for anyone to read for as long as anyone wants. It's all up to the recipient.


---
# Have a signature

Please create an email signature

- Name
- Title
- Link to your website

--

Try **not** to include inspirational quotes, pictures, extra clutter



<!-- New Section -->
---
class: inverse, center, middle
name: meetings

# Meetings

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>
