---
title: "1st Year Workshop"
subtitle: "Who is here and who might leave?"
author: Ian McCarthy, Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: ["macros.js","https://platform.twitter.com/widgets.js"]
---
class: inverse, center, middle
name: basics

# What a great group!

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```


---
# Our goal

What a great, diverse group! We want **EVERYONE** to leave here with a PhD in Economics and on their way to the job that **THEY WANT**

---
# Our reality

- But inevitably, not everyone finishes the program:
    - Awarded 89 Economics PhD degrees since 1993 and 31 Economics MA degrees
    - Cumulatively 61 people lost at various stages
    - 17% probability of failing the 1st-year core exams
    - 54% probability of leaving the program for any reason, at any time
- Who is in this 54%?


---
class: clear

<center>
<blockquote class="twitter-tweet" data-lang="en" width="400" height="300"><p lang="en" dir="ltr"><a href="https://twitter.com/B_DiazCastro/status/1557260048728031234?s=20&t=o5N542U6wJRpFKVUWf78Qg"></a></blockquote><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</center>


---
class: inverse, center, middle
name: who

# Who doesn't finish?

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Who doesn't finish?

1. Match with a PhD
2. Match with the program
3. Allocation of effort


---
# 1. Match with a PhD

- Challenge of graduate school can be a shock
- Academia is a unique work environment, may not fit with your prior
- People change and evolve

--

Knowing yourself and knowing the profession are important things. Leaving the program for these reasons is not what I would call a failure.


---
# 2. Match with the program

- Interests don't align with available expertise
- Faculty move
- People change and evolve!
- Program is not supportive

--

These are clear failures, but they are failures on our part!

---
# 3. Effort allocation

- Inefficient use of available time
- Not committed enough
- Burn out
    
--

Very personal issues. Everyone works and handles stress differently. But we are here to help however we can.


