---
title: "1st Year Workshop"
subtitle: "Who is here and who might leave?"
author: "Ian McCarthy, Emory University"
institute: "Economics PhD Professionalism Workshop"
---

# What a great group! {background-color="#23373B"}

# Who are you?

- 11 selected out of **407** applicants!
- 6 Masters degrees
- 8 different countries, 5 different continents


---

# Our goal

What a great, diverse group! We want **EVERYONE** to leave here with a PhD in Economics and on their way to the job that **THEY WANT**

---

# Our reality

- But inevitably, not everyone finishes the program:
    - Awarded 91 Economics PhD degrees since 1993 and 31 Economics MA degrees
    - Cumulatively 61 people lost at various stages
    - 17% probability of failing the 1st-year core exams
    - 54% probability of leaving the program for any reason, at any time
- Who is in this 54%?


---

# Who doesn't finish? {background-color="#23373B"}

# Who doesn't finish?

1. Match with a PhD
2. Match with the program
3. Allocation of effort


---

# 1. Match with a PhD

- Challenge of graduate school can be a shock
- Academia is a unique work environment, may not fit with your prior
- People change and evolve

. . .

Knowing yourself and knowing the profession are important things. Leaving the program for these reasons is not what I would call a failure.


---

# 2. Match with the program

- Interests don't align with available expertise
- Faculty move
- People change and evolve!
- Program is not supportive

. . .

These are clear failures, but they are failures on our part!

---

# 3. Effort allocation

- Inefficient use of available time
- Not committed enough
- Burn out

. . .

Very personal issues. Everyone works and handles stress differently. But we are here to help however we can.
