---
title: "3rd Year Workshop"
subtitle: "Backing up your work and data"
author: Ian McCarthy, Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```

# Backing up

How do you back up your work? Lots of ways:

1. External hard drives

2. Cloud services

3. Automatic back up services

---
# External hard drives

.pull-left[
Pros:
- Affordable and fully in your control
- Data remain private
]

.pull-right[
Cons:
- Only backed up at certain intervals
- Can be slow
- Data are all in the same physical place
]


--
Crashes will inevitably happen between backups

---
# Cloud services

Lots of cloud services like DropBox, Google Drive, OneDrive

.pull-left[
Pros:
- Works really well and painlessly
- Easy to share when needed
]

.pull-right[
Cons:
- Can get expensive over time
- Can't backup private or restricted data
]

---
# Offsite hard drives

Just build your own network!

.pull-left[
Pros:
- Data stays with you
- Backup in real-time
- Redundancies built-in to network configuration
]

.pull-right[
Cons:
- Expensive to buy
- Harder to setup
]


---
# My backup system

- I use a Synology 4-bay NAS DiskStation 
- "Synology Drive" to sync files across locations
- Synology Hybrid RAID (because I'm not a network engineer)
- Sync with Google Drive for some individual files or folders (papers to read, bibtex library)