---
title: "3rd Year Workshop"
subtitle: "Organizing your projects"
author: Ian McCarthy, Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---
class: inverse, center, middle
name: workflow

# Workflow

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```


---
# Workflow

- Workflow is a system to make it easier on your brain to do your work
- Don't waste time finding things or trying to remember that great idea you had
- We'll work toward an organized and systematic workflow that ensures replicability and minimizes mistakes
- **Keystone habit**: a way to organize all other good habits

---
# Getting organized

In the etiquette section, we talked about some very general tips for staying organized. This will be specific to research. Here, we'll cover strategies to organize...
1. notes for your research project
2. your project folders
3. notes on papers you've read
4. papers you're citing

---
class: inverse, center, middle
name: high-level

# Organizing Your Research

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Project notebooks

- Organize your projects into notebooks (or folders) of some kind
- Digital options: OneNote, Evernote, Notion, Google Keep, just text files in a folder
- Other options: Bullet journals (pen and paper, gasp!)

---
count: false

# Project notebooks

Here's my system:
- Three main research categories: 1) pending research; 2) ongoing research; and 3) completed research
- **Pending research** is for ideas
    - Google Keep note
    - After some thought, transition to individual notebook/folder (ReMarkable)
    - After more thought, transition to **ongoing research** (if viable)

---
count: false

# Project notebooks

Here's my system:
- Three main research categories: 1) pending research; 2) ongoing research; and 3) completed research
- **Pending research** is for ideas
- **Ongoing research** is for actual working projects
    - Section for each project
    - Subsections for "meeting notes" (if co-authored) and "ideas/thoughts"
    

---
count: false

# Project notebooks

Here's my system:
- Three main research categories: 1) pending research; 2) ongoing research; and 3) completed research
- **Pending research** is for ideas
- **Ongoing research** is for actual working projects
- **Completed research** is for, you guessed it, completed projects
    - After paper is officially accepted and all supporting documentation finalized


---
class: inverse, center, middle
name: low-level

# Organizing One Project

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Project folders

Key is to have a system where files are named appropriately and everything is easily accessible. Basically it's a closet for your research.

---
count: false

# Project folders

.pre[
```
project
|   README.md
|   RunRender.Rmd
|   paper.Rmd
|   abstract.Rmd
|   presentation.Rmd
|   BibTeX.tex (symbolic link)
|
|---analysis
|   |   _analysis.R
|   |   1_sumstats.R
|   |   2_awesome-stuff.R
|
|---data-code
|   |   _build-data.R
|   |   1_data1.R
|   |   2_data2.R
|   |   final_dat1.Rds (or csv)
|   |   final_dat2.Rds (or csv)
|
|---data
|   |   input (symbolic links)
|   |   output (analytic data sets)
|
|---results
|   |   table1.tex
|   |   figure1.png
```
]

---
count: false

# Project folders

- Project need not start out perfectly organized
- Think of the folder/file structure as your kitchen
    - It will get dirty
    - Don't let it get so dirty that you forget stuff
    - Clean up regularly!

---
class: inverse, center, middle
name: other-papers

# Organizing Others' Research

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Reading papers

- We read lots of papers. That's part of the job and critical to doing good work. 
- Want to avoid losing our notes on papers we've already read
- Lots of ways to store PDFs and handwritten notes
    - OneNote "learning" notebook
    - Several Mac/iPad options
    - Research Rabbit
    - ReMarkable tablets (my strategy)
    

---
# Citation managers

- Lots of software options: Zotero, Mendeley, EndNote Web
- My system: Zotero
  - Cloud backup with papers linked to citations
  - Export to "BibTeX_Library.bib" folder updated on desktop
  - Sync with Google Drive
  - Pull down from Google Drive with Overleaf or RMarkdown
