---
title: "3rd Year Workshop"
subtitle: "Write better"
author: Ian McCarthy, Emory University
date: Economics PhD Professionalism Workshop #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate)
```

# How to write?

I wish I knew!

--
But there are some basic rules that might help

---
# Introduction

The introduction is critical. It is the most important thing you'll write for any paper. Make it awesome!


---
count: false

# Introduction [formula](https://www.albany.edu/spatial/training/5-The%20Introduction%20Formula.pdf)

1. **The Hook!** Why should anyone care about this at all? What big issue are you dealing with?
2. **Question.** What are you actually going to do? What is your actual research question? Doesn't need context.
3. **Context.** What are the key things that other people have done? What literature should a reader know in order to understand your contribution? 
4. **Contribution.** What are you doing differently? Should be in context of the existing literature.
5. **Expand.** I've added this. Modern applied papers (for better or worse) need to talk about some key additional findings in the intro (mechanisms, robustness, and policy implications, etc.).


---
# Paper structure

We've all seen the "standard" applied econ paper structure:

.pull-left[
1. Introduction
2. Theoretical motivation or institutional details
3. Data
4. Estimation
5. Results
6. Conclusion
]

---
count: false

# Paper structure

We've all seen the "standard" applied econ paper structure:

.pull-left[
1. Introduction
2. Theoretical motivation or institutional details
3. Data
4. Estimation
5. Results
6. Conclusion
]

.pull-right[
I **do not** like this formula...
- Fine as outline
- Too rigid and boring
- Need better **story**
]

---
count: false

# Paper structure

- Take a look at any good applied paper in the last several years
- Most will start similarly (intro, theory/policy details, maybe data)
- Then deviate based on relevant analyses and estimation strategies